import os
import streamlit as st

from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

## API Keys
openai_api_key = os.getenv("OPENAI_API_KEY")
ollama_api_key = os.getenv("OLLAMA_API_KEY")

## LLMs
# OpenAI cloud LLM
llm_openai_cloud = ChatOpenAI(
    model="gpt-5-nano", 
    api_key=openai_api_key, 
    temperature=0                                           # Controls randomness: 0 = deterministic/focused, higher values = more creative/random
)

# Ollama cloud LLM
llm_ollama_cloud = ChatOllama(
    model="gpt-oss:20b",
    base_url="https://ollama.com",
    headers={
        # Adds API key to request headers. Example: Authorization: Bearer xxxxx
        "Authorization": f"Bearer {ollama_api_key}"
    },
    temperature=0
)

## PROMPT TEMPLATE
# System role -> sets assistant behavior/context
# Human role  -> user input/question
# AI role     -> model response generated by LLM

# PromptTemplate:
#     Everything is one plain text prompt.
#     There is no role separation.
#
# ChatPromptTemplate:
#     Creates chat messages with roles.
#     Instructions, user input, and previous AI responses can be separated.
#
# ChatPromptTemplate roles:
#
#   ("system", "Instruction/context")
#       Sets the model's behavior, role, rules, and overall context.
#       Tells the model how it should behave.
#       Example: "You are an Agile Coach. Answer clearly."
#
#   ("human", "User message")
#       Represents the actual user question/input.
#       Tells what the user is asking now.
#       Example: "What is sprint planning?"
#
#   ("ai", "Previous assistant response")
#       Represents a previous model/assistant reply.
#       Tells what the assistant said before.
#       Useful when adding chat history or few-shot examples.
#       Example: "Sprint planning is a Scrum event where the team plans work for the sprint."

prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are a Scrum Coach. Answer questions related to Scrum clearly, practically, and beginner-friendly."),
    ("human", "{user_question}")
])

## Streamlit UI
st.title("Scrum Guide")

# Select LLM model
selected_provider = st.selectbox(
    "Choose LLM provider",
    options=["OpenAI Cloud", "Ollama Cloud"],
    index=0                                                 # Default: OpenAI Cloud. Use index=1 to default to Ollama Cloud
)

# input fields
user_question = st.text_input("Enter question related to Scrum")

# Select LLM based on user selection
if selected_provider == "OpenAI Cloud":
    llm_selected = llm_openai_cloud
else:
    llm_selected = llm_ollama_cloud

## LCEL chain
# chain: user_question -> chat prompt -> selected LLM -> plain string response
chain = prompt_template | llm_selected | StrOutputParser()

## Generate
# Current app has no chat history
if st.button("Ask"):
    if user_question:
        try:
            with st.spinner(f"Thinking using {selected_provider}..."):
                response = chain.invoke({
                    "user_question": user_question
                })
           
            st.subheader("Answer")
            st.write(response)

        except Exception as e:
            st.error(f"Error: {e}")
            st.exception(e)
    else:
        st.warning("Please enter a question")
## Run:
# cd D:\dev\github\agentic-ai-langchaindemo\s7_maintaining-chathistory
# python -m streamlit run 1_chatprompttemplate_demo.py
# http://localhost:8501/      




## Ask two questions without chat history
#
# Current app has no chat history.
# Each button click sends only:
#     1. system message
#     2. latest human message
#
# Previous human questions and AI answers are NOT sent again.


# Round 1:
# System:
#     You are a Scrum Coach. Answer questions related to Scrum clearly and practically.
#
# Human:
#     What is Scrum?
#
# AI:
#     Scrum is a lightweight, evidence-based framework for building complex products.
#     It focuses on ...


# Round 2:
# System:
#     You are a Scrum Coach. Answer questions related to Scrum clearly and practically.
#
# Human:
#     Can you summarise this in two sentences?
#
# AI:
#     I’d be happy to, but I need the text you’d like summarized.
#     Could you share the content?
#
# Reason:
#     The model does not receive the Round 1 question/answer.
#     So it does not know what "this" refers to.
#
# Note:
#     Sometimes the model may still answer by guessing from the system role/context.
#     But that is not real memory/chat history.