import os
import streamlit as st

from langchain_openai import ChatOpenAI
from langchain_ollama import OllamaLLM, ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

## LLM
# OpenAI cloud api
# export/setx OPENAI_API_KEY="your_key"
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
openai_llm_cloud = ChatOpenAI(model="gpt-4o-mini", api_key=OPENAI_API_KEY, temperature=0)

# Ollama cloud api
ollama_llm_local = ChatOllama(model="tinyllama")
ollama_llm_cloud = ChatOllama(
    model="gpt-oss:20b",
    base_url="https://ollama.com",
    headers={                                                # Adds API key to request headers. Ex: Authorization: Bearer xxxxx
        "Authorization":
            f"Bearer {os.environ.get('OLLAMA_API_KEY')}"
    }
)

## PROMPT TEMPLATE
# System role -> sets assistant behavior/context
# Human role  -> user input/question
# AI role     -> model response generated by LLM

# PromptTemplate:
#     Everything is one plain text prompt.
#     There is no role separation.
#
# ChatPromptTemplate:
#     Creates chat messages with roles.
#     Instructions, user input, and previous AI responses can be separated.
#
# ChatPromptTemplate roles:
#
#   ("system", "Instruction/context")
#       Sets the model's behavior, role, rules, and overall context.
#       Tells the model how it should behave.
#       Example: "You are an Agile Coach. Answer clearly."
#
#   ("human", "User message")
#       Represents the actual user question/input.
#       Tells what the user is asking now.
#       Example: "What is sprint planning?"
#
#   ("ai", "Previous assistant response")
#       Represents a previous model/assistant reply.
#       Tells what the assistant said before.
#       Useful when adding chat history or few-shot examples.
#       Example: "Sprint planning is a Scrum event where the team plans work for the sprint."

prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are a Scrum Coach. Answer questions related to Scrum clearly, practically, and beginner-friendly."),
    ("human", "{user_question}")
])

## LCEL chain
chain = prompt_template | ollama_llm_cloud | StrOutputParser()

## Streamlit UI
st.title("Scrum Guide")
user_question = st.text_input("Enter question related to Scrum")

## Generate
# Current app has no chat history
if st.button("Ask"):
    if user_question:
        try:
            response = chain.invoke({
                "user_question": user_question
            })
            st.subheader("Answer")
            st.markdown(response)
        except Exception as e:
            st.error(f"Error: {e}")
    else:
        st.warning("Please enter a question")
## Run:
# cd D:\dev\github\agentic-ai-langchaindemo\s7_maintaining-chathistory
# python -m streamlit run 1_chatprompttemplate_demo.py
# http://localhost:8501/      




## Ask two questions without chat history
#
# Current app has no chat history.
# Each button click sends only:
#     1. system message
#     2. latest human message
#
# Previous human questions and AI answers are NOT sent again.


# Round 1:
# System:
#     You are a Scrum Coach. Answer questions related to Scrum clearly and practically.
#
# Human:
#     What is Scrum?
#
# AI:
#     Scrum is a lightweight, evidence-based framework for building complex products.
#     It focuses on ...


# Round 2:
# System:
#     You are a Scrum Coach. Answer questions related to Scrum clearly and practically.
#
# Human:
#     Can you summarise this in two sentences?
#
# AI:
#     I’d be happy to, but I need the text you’d like summarized.
#     Could you share the content?
#
# Reason:
#     The model does not receive the Round 1 question/answer.
#     So it does not know what "this" refers to.
#
# Note:
#     Sometimes the model may still answer by guessing from the system role/context.
#     But that is not real memory/chat history.